[package]
name = "tokenizerscpp"
version = "0.1.0"
edition = "2021"

[lib]
name = "tokenizerscpp"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
tokenizers = "0.13.1"

[build-dependencies]
cxx-build = "1.0"